apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: { name: fastapi-role }
rules:
  - apiGroups: [""]
    resources: ["pods","services"]
    verbs: ["get","list","watch","create","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: { name: fastapi-rolebinding }
subjects:
  - kind: ServiceAccount
    name: fastapi-sa
roleRef:
  kind: Role
  name: fastapi-role
  apiGroup: rbac.authorization.k8s.io